name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: macos

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: run install, start and test
        run: |
          npm install
          npm start
          npm run test
          